CREATE TABLE IF NOT EXISTS TrafficMeasurement (
    day VARCHAR,
    interval INTEGER,
    detid VARCHAR,
    flow FLOAT,
    occ FLOAT,
    error INTEGER,
    city VARCHAR,
    speed FLOAT
);

CREATE TABLE IF NOT EXISTS DetectorLocation (
    detid VARCHAR,
    length FLOAT,
    pos FLOAT,
    fclass VARCHAR,
    road VARCHAR,
    limit_ VARCHAR,
    citycode VARCHAR,
    lanes INTEGER,
    linkid INTEGER,
    long FLOAT,
    lat FLOAT,
    PRIMARY KEY (detid, fclass, citycode)
);

CREATE TABLE IF NOT EXISTS DetectorLink (
    long FLOAT,
    lat FLOAT,
    order_ INTEGER,
    piece VARCHAR,
    linkid VARCHAR,
    group_ VARCHAR,
    citycode VARCHAR
    -- PRIMARY KEY (order_, linkid, citycode)
);

CREATE TABLE IF NOT EXISTS Zugfahrt (
    BETRIEBSTAG VARCHAR,
    FAHRT_BEZEICHNER VARCHAR,
    BETREIBER_ID VARCHAR,
    BETREIBER_ABK VARCHAR,
    BETREIBER_NAME VARCHAR,
    PRODUKT_ID VARCHAR,
    LINIEN_ID INTEGER,
    LINIEN_TEXT VARCHAR,
    UMLAUF_ID INTEGER,
    VERKEHRSMITTEL_TEXT VARCHAR,
    ZUSATZFAHRT_TF BOOLEAN,
    FAELLT_AUS_TF BOOLEAN,
    BPUIC INTEGER,
    HALTESTELLEN_NAME VARCHAR,
    ANKUNFTSZEIT VARCHAR,
    AN_PROGNOSE VARCHAR,
    AN_PROGNOSE_STATUS VARCHAR,
    ABFAHRTSZEIT VARCHAR,
    AB_PROGNOSE VARCHAR,
    AB_PROGNOSE_STATUS VARCHAR,
    DURCHFAHRT_TF BOOLEAN
);
